version: "3.8"

services:
  web:
    build: .
    container_name: help-gpt
    ports:
      - "8080:8080"
    environment:
      # !!! НЕ храните реальный ключ в репозитории
      OPENAI_API_KEY: ${OPENAI_API_KEY}   # <-- ключ берём из переменной стека
      MODEL: "deepseek/deepseek-chat"  # или, например: anthropic/claude-3.5-sonnet
      APP_NAME: "help-gpt"
      APP_URL: "http://localhost:8080"
    restart: unless-stopped
    # УБРАЛ том, чтобы не затирать код. Если нужен — маунтите другую директорию.
    # volumes:
    #   - appdata:/data

# volumes:
#   appdata:
