version: "3.8"

services:
  web:
    build: .
    container_name: help-gpt
    ports:
      - "8080:8080"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}   # <-- ключ берём из переменной стека
      MODEL: "deepseek/deepseek-chat"     # или, например: anthropic/claude-3.5-sonnet
      APP_NAME: "help-gpt"
      APP_URL: "http://localhost:8080"
      TZ: "Europe/Moscow"                 # <-- локальная таймзона
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro  # <-- берём время с хоста
      - /etc/timezone:/etc/timezone:ro    # <-- и таймзону с хоста
