version: "3.8"

services:
  web:
    build: .
    container_name: help-gpt
    ports:
      - "8080:8080"

    # подключаем .env к этому сервису
    env_file:
      - .env

environment:
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  MODEL: "deepseek/deepseek-chat"
  APP_NAME: "help-gpt"
  APP_URL: "http://localhost:8080"
  TZ: "Europe/Moscow"


    restart: unless-stopped

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
