version: "3.8"

services:
  web:
    build: .
    container_name: help-gpt
    ports:
      - "8080:8080"
    environment:
      # !!! НЕ храните реальный ключ в репозитории
      OPENAI_API_KEY: "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"   # ключ OpenRouter
      MODEL: "google/gemini-1.5-flash"  # или, например: anthropic/claude-3.5-sonnet
      APP_NAME: "help-gpt"
      APP_URL: "http://localhost:8080"
    restart: unless-stopped
    # УБРАЛ том, чтобы не затирать код. Если нужен — маунтите другую директорию.
    # volumes:
    #   - appdata:/data

# volumes:
#   appdata:
